spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ddlgen;MODE=MySQL   # MySQL 문법 호환 모드
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: build/generated-schema.sql
      jakarta.persistence.database-product-name: MySQL
